using System.Text;
using System.Text.Json.Nodes;

namespace Wip.Tests.ComposeCompat;

/// <summary>
/// Renders tests/compose-compat/differences.md from the matrix and the two live
/// interpretations, so the human-readable difference list cannot drift from what the suite
/// actually compares.
/// </summary>
internal static class ComposeCompatReport
{
    internal static string Render()
    {
        var matrix = ComposeCompatMatrix.Load();
        var builder = new StringBuilder();

        builder.Append("""
            # wip ↔ Microsoft `wslc compose`: recorded differences

            <!--
              Generated by Wip.Tests.ComposeUpstreamCompatTests. Do not edit by hand:

                WIP_COMPOSE_COMPAT_UPDATE=1 dotnet test --project tests/Wip.Tests/Wip.Tests.csproj

              Edit tests/compose-compat/matrix.json (statuses and notes) or the fixtures, then
              re-record. tests/compose-compat/README.md explains the workflow.
            -->

            Upstream is pinned at the commit named in
            [`upstream/PINNED.md`](upstream/PINNED.md). `wip` column and `upstream` column are
            the two readings of the same fixture, projected onto the one feature named on the
            row.


            """);

        builder.Append(Summary(matrix));
        builder.Append('\n');

        foreach (var status in ComposeCompatMatrix.Statuses)
        {
            builder.Append(Section(matrix, status));
        }

        builder.Append(Fixtures(matrix));
        return builder.ToString();
    }

    private static string Summary(ComposeCompatMatrix matrix)
    {
        var counts = ComposeCompatMatrix.Statuses.ToDictionary(
            status => status,
            status => matrix.FixtureNames()
                .SelectMany(fixture => matrix.Features(fixture).Select(pair => matrix.Status(fixture, pair.Key)))
                .Count(entry => entry == status),
            StringComparer.Ordinal);

        var builder = new StringBuilder("## Summary\n\n| status | entries |\n|---|---|\n");
        foreach (var status in ComposeCompatMatrix.Statuses)
        {
            builder.Append($"| `{status}` | {counts[status]} |\n");
        }

        return builder.ToString();
    }

    private static string Section(ComposeCompatMatrix matrix, string status)
    {
        var rows = new List<string>();
        foreach (var fixture in matrix.FixtureNames().Order(StringComparer.Ordinal))
        {
            var wip = WipComposeInterpreter.Interpret(fixture);
            var upstream = UpstreamComposeInterpreter.Interpret(fixture);

            foreach (var (feature, _) in matrix.Features(fixture))
            {
                if (matrix.Status(fixture, feature) != status)
                {
                    continue;
                }

                rows.Add($"""
                    ### `{feature}` — [{fixture}](fixtures/{fixture}/)

                    - **wip**: {Summarize(wip.Projection(feature))}
                    - **upstream**: {Summarize(upstream.Projection(feature))}
                    - **status**: `{status}`
                    - **note**: {matrix.Note(fixture, feature)}


                    """);
            }
        }

        if (rows.Count == 0)
        {
            return string.Empty;
        }

        return $"## {Heading(status)}\n\n" + string.Join(string.Empty, rows);
    }

    private static string Heading(string status) => status switch
    {
        "compatible" => "Compatible — both implementations agree",
        "known-difference" => "Known differences — both have an opinion, and they differ",
        "upstream-unsupported" => "Upstream unsupported — Compose behaviour `wslc compose` rejects today",
        "wip-only" => "wip-only — wip implements it, upstream has no notion of it",
        _ => status,
    };

    private static string Fixtures(ComposeCompatMatrix matrix)
    {
        var builder = new StringBuilder("## Fixture index\n\n| fixture | what it is for | features tracked |\n|---|---|---|\n");
        foreach (var fixture in matrix.FixtureNames().Order(StringComparer.Ordinal))
        {
            var features = string.Join(", ", matrix.Features(fixture).Select(pair => $"`{pair.Key}`"));
            builder.Append($"| [{fixture}](fixtures/{fixture}/) | {matrix.Description(fixture)} | {features} |\n");
        }

        return builder.ToString();
    }

    /// <summary>One line of JSON, with the pipe escaped so it survives a Markdown table cell.</summary>
    private static string Summarize(JsonNode node)
    {
        var text = node.ToJsonString();
        return $"`{text.Replace("|", "\\|", StringComparison.Ordinal)}`";
    }
}
