using System.Text.RegularExpressions;

namespace Wip.Platform;

/// <summary>
/// Translates host paths between the form Windows hands wip and the form wslc is given.
/// </summary>
/// <remarks>
/// <para>
/// This is the single place the migration's open question lands, and it is deliberately one
/// function so that answering the question is a local change. wip.exe runs on the Windows
/// side, but is typically invoked from a WSL2 shell, so a project under <c>~/proj</c> gives
/// the process a UNC working directory (<c>\\wsl.localhost\Ubuntu\home\u\proj</c>). Three
/// call sites then hand that path to wslc: the <c>sync:</c> source mount, <c>volumes:</c>
/// bind mounts, and the build context.
/// </para>
/// <para>
/// What wslc accepts has not been measured yet — see docs/csharp-migration-plan.md §3.2,
/// Phase 0 Spike 1. This implements branch (a) of that decision tree, translating a UNC
/// path back to the Linux path it denotes, on the reasoning that wslc runs containers inside
/// a WSL2 VM and therefore speaks Linux paths. If the spike shows otherwise, this method is
/// what changes; nothing else needs to know.
/// </para>
/// <para>
/// On non-Windows hosts every path passes through untouched, which is what keeps the golden
/// corpus comparable: the fixtures were generated by the Ruby build running inside WSL.
/// </para>
/// </remarks>
public static partial class WslPath
{
    /// <summary>
    /// Converts a host path into the form handed to wslc on a command line.
    /// </summary>
    public static string ForWslc(string path)
    {
        if (!OperatingSystem.IsWindows())
        {
            return path;
        }

        var match = UncPattern().Match(path);
        if (!match.Success)
        {
            return path;
        }

        var remainder = match.Groups[2].Value.Replace('\\', '/');
        return remainder.Length == 0 ? "/" : $"/{remainder.TrimStart('/')}";
    }

    /// <summary>Whether <paramref name="path"/> points inside a WSL distribution's filesystem.</summary>
    public static bool IsWslPath(string path) => OperatingSystem.IsWindows() && UncPattern().IsMatch(path);

    /// <summary>The distribution name in a WSL UNC path, or null when it is not one.</summary>
    public static string? DistributionOf(string path)
    {
        var match = UncPattern().Match(path);
        return match.Success ? match.Groups[1].Value : null;
    }

    // Both spellings are in circulation: \\wsl$\ predates \\wsl.localhost\ and still
    // resolves, so a working directory can arrive as either.
    [GeneratedRegex(@"\A\\\\wsl(?:\.localhost|\$)\\([^\\]+)(?:\\(.*))?\z", RegexOptions.IgnoreCase)]
    private static partial Regex UncPattern();
}
