using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using Wip.Configuration;
using Wip.Execution;
using Wip.Platform;
using Wip.Yaml;

namespace Wip.Tests;

/// <summary>
/// Replays every operation the Ruby implementation recorded for each config fixture. This is
/// the load-bearing parity check: if the argv arrays match, the commands wip actually runs
/// match. See tests/golden/README.md.
/// </summary>
public partial class FixtureGoldenTests
{
    private const string Wslc = "wslc.exe";

    public static IEnumerable<object[]> Operations() => GoldenCorpus.FixtureOperations();

    [Theory]
    [MemberData(nameof(Operations))]
    public void ProducesTheSameResultRubyDid(string fixture, string operation, string expectedJson)
    {
        // The corpus was generated by the Ruby build running inside WSL, so its host paths
        // are Linux paths. On Windows those same expectations resolve to C:\... or a UNC
        // path -- the documented divergence in tests/golden/README.md, not a regression. The
        // rest of the corpus still runs on both platforms.
        Assert.SkipWhen(
            OperatingSystem.IsWindows() && expectedJson.Contains("FIXTURE", StringComparison.Ordinal),
            "host-path expectation; see docs/csharp-migration-plan.md §3");

        var expected = JsonNode.Parse(expectedJson)!.AsObject();
        var directory = Path.Combine(GoldenCorpus.CasesDirectory, fixture);

        object? actual;
        try
        {
            actual = Invoke(directory, operation);
        }
        catch (WipException exception)
        {
            var error = expected["error"]?.GetValue<string>();
            Assert.True(
                error is not null,
                $"{fixture}/{operation}: expected a value but threw: {exception.Message}");
            Assert.Equal(GoldenCorpus.Resolve(error!, fixture), exception.Message);
            return;
        }

        Assert.True(
            expected.ContainsKey("ok"),
            $"{fixture}/{operation}: expected an error but got {RubyJson.Canonical(RubyJson.ToJson(actual))}");

        var want = RubyJson.Canonical(Resolve(expected["ok"], fixture));
        Assert.Equal(want, RubyJson.Canonical(RubyJson.ToJson(actual)));
    }

    /// <summary>Substitutes the fixture directory back into the recorded &lt;FIXTURE&gt; placeholders.</summary>
    private static JsonNode? Resolve(JsonNode? node, string fixture) =>
        node is null ? null : JsonNode.Parse(GoldenCorpus.Resolve(node.ToJsonString(), fixture));

    private static object? Invoke(string directory, string operation)
    {
        var envFile = Path.Combine(directory, ".env");
        var dotenv = new DotenvLoader(envFile).Load();
        var config = new ConfigLoader(
            path: Path.Combine(directory, "wip.yml"),
            envFile: File.Exists(envFile) ? envFile : null).Load();

        var tty = new CommandBuilder(Wslc, config, new FakeEnvironment(true), dotenv);
        var notty = new CommandBuilder(Wslc, config, new FakeEnvironment(false), dotenv);

        var indexed = IndexedOperation().Match(operation);
        if (indexed.Success)
        {
            return InvokeIndexed(config, tty, indexed.Groups[1].Value, indexed.Groups[2].Value);
        }

        return operation switch
        {
            "config.to_h" => config.ToMapping(),
            "config.to_h.unredacted" => config.ToMapping(redact: false),
            "config.mode" => config.Mode,
            "config.container" => config.Container,
            "config.network" => config.Network,
            "config.wslc_command" => config.WslcCommand,
            "config.dependencies.keys" => config.Dependencies.Keys.ToList<object?>(),
            "config.commands.keys" => config.Commands.Keys.ToList<object?>(),
            "config.compose_build_specs" => config.ComposeBuildSpecs,
            "config.sync.to_h" => config.Sync?.ToMapping(),
            "dotenv" => dotenv,

            "builder.up.detached" => tty.Up(detach: true),
            "builder.up.attached.tty" => tty.Up(detach: false),
            "builder.up.attached.notty" => notty.Up(detach: false),
            "builder.start.detached" => tty.Start(detach: true),
            "builder.start.attached" => tty.Start(detach: false),
            "builder.find" => tty.Find(),
            "builder.stop" => tty.Stop(),
            "builder.remove" => tty.Remove(),
            "builder.network_create" => tty.NetworkCreate(),
            "builder.network_list" => tty.NetworkList(),
            "builder.exec.tty" => tty.Exec(["bash", "-lc", "ls"], interactive: true),
            "builder.exec.notty" => notty.Exec(["bash", "-lc", "ls"], interactive: true),
            "builder.exec.noninteractive" => tty.Exec(["bash", "-lc", "ls"], interactive: false),
            "builder.run.tty" => tty.Run(["ls", "-la"], interactive: true),
            "builder.run.notty" => notty.Run(["ls", "-la"], interactive: true),
            "builder.build" => tty.Build(config.Command("build")),
            "builder.build.extra" => tty.Build(config.Command("build"), ["--no-cache"]),
            "builder.sync_run" => tty.SyncRun(),
            "builder.sync_exec" => tty.SyncExec(),
            "builder.sync_build" => tty.SyncBuild("."),
            "builder.logs.follow" => tty.Logs("web", follow: true),
            "builder.logs.nofollow" => tty.Logs("web", follow: false),

            _ => throw new InvalidOperationException($"Unhandled golden operation: {operation}"),
        };
    }

    private static object? InvokeIndexed(Config config, CommandBuilder builder, string operation, string name) =>
        operation switch
        {
            "builder.dependency_up" => builder.DependencyUp(name),
            "builder.dependency_up.attached" => builder.DependencyUp(name, detach: false),
            "builder.dependency_start" => builder.DependencyStart(name),
            "builder.dependency_find" => builder.DependencyFind(name),
            "builder.dependency_stop" => builder.DependencyStop(name),
            "builder.dependency_remove" => builder.DependencyRemove(name),
            "builder.custom" => builder.Custom(name, []),
            "builder.custom.args" => builder.Custom(name, ["--trace", "extra"]),
            "config.command" => config.Command(name),
            _ => throw new InvalidOperationException($"Unhandled golden operation: {operation}[{name}]"),
        };

    [GeneratedRegex(@"\A(.+)\[(.*)\]\z")]
    private static partial Regex IndexedOperation();

    private sealed class FakeEnvironment : IEnvironment
    {
        internal FakeEnvironment(bool interactive) => IsInteractive = interactive;

        public bool IsInteractive { get; }

        public bool IsWsl2 => true;

        public string Architecture => "linux/amd64";
    }
}
