using System.Text.Json.Nodes;
using Wip.Build;
using Wip.Compose;
using Wip.Diagnostics;
using Wip.Execution;

namespace Wip.Tests;

/// <summary>
/// Table-driven parity checks for the pure functions, against expectations generated by the
/// Ruby implementation. See tests/golden/README.md.
/// </summary>
public class UnitGoldenTests
{
    public static IEnumerable<object[]> VariableInterpolationCases() =>
        GoldenCorpus.UnitCases("variable_interpolation");

    [Theory]
    [MemberData(nameof(VariableInterpolationCases))]
    public void InterpolatesTheSameWayRubyDid(string caseJson)
    {
        var entry = JsonNode.Parse(caseJson)!.AsObject();
        var environment = GoldenCorpus.LoadUnit("variable_interpolation")["env"]!.AsObject()
            .ToDictionary(pair => pair.Key, pair => pair.Value!.GetValue<string>(), StringComparer.Ordinal);

        var expected = entry["result"]!["ok"]!.GetValue<string>();
        Assert.Equal(expected, VariableInterpolation.Call(entry["input"]!.GetValue<string>(), environment));
    }

    public static IEnumerable<object[]> DockerIgnoreCases() => GoldenCorpus.UnitCases("dockerignore");

    [Theory]
    [MemberData(nameof(DockerIgnoreCases))]
    public void MatchesDockerIgnoreTheSameWayRubyDid(string caseJson)
    {
        var entry = JsonNode.Parse(caseJson)!.AsObject();
        var patterns = GoldenCorpus.LoadUnit("dockerignore")["patterns"]!.GetValue<string>();
        var ignore = DockerIgnore.FromLines(patterns.Split('\n'));

        var path = entry["path"]!.GetValue<string>();
        Assert.Equal(entry["ignored"]!.GetValue<bool>(), ignore.Ignored(path));
        Assert.Equal(entry["prunable"]!.GetValue<bool>(), ignore.Prunable(path));
    }

    public static IEnumerable<object[]> ErrorInterpreterCases() => GoldenCorpus.UnitCases("error_interpreter");

    [Theory]
    [MemberData(nameof(ErrorInterpreterCases))]
    public void InterpretsErrorsTheSameWayRubyDid(string caseJson)
    {
        var entry = JsonNode.Parse(caseJson)!.AsObject();
        var architecture = GoldenCorpus.LoadUnit("error_interpreter")["architecture"]!.GetValue<string>();
        var interpreter = new ErrorInterpreter(architecture);

        var hint = entry["hint"];
        var expected = hint is null ? null : hint.GetValue<string>();
        Assert.Equal(expected, interpreter.Interpret(entry["input"]!.GetValue<string>()));
    }

    public static IEnumerable<object[]> CommandDisplayCases() =>
        GoldenCorpus.UnitCases("command_display", arrayProperty: null);

    [Theory]
    [MemberData(nameof(CommandDisplayCases))]
    public void RendersDebugOutputTheSameWayRubyDid(string caseJson)
    {
        var entry = JsonNode.Parse(caseJson)!.AsObject();
        var command = entry["command"]!.AsArray().Select(value => value!.GetValue<string>()).ToArray();

        Assert.Equal(entry["display"]!.GetValue<string>(), CommandDisplay.ForDebug(command));
    }
}
